site_name: William Banks — Technical Writing Portfolio
site_description: Selected samples demonstrating how-to, conceptual, and reference documentation using a docs-as-code workflow.
site_url: https://bankswe-portfolio.github.io/tech-writing-portfolio
repo_url: https://github.com/bankswe-portfolio/tech-writing-portfolio
edit_uri: blob/main/docs/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.snippets
nav:
  - Home: index.md
  - Case Studies:
    - Mondoo - cnquery Practical Guide: case-studies\cnquery-practical-guide_mkdocs.md
    - Horizon3.ai - NodeZero Tripwires Redline: case-studies\horizon3ai-tripwires-redline.md
    - LangChain - Agents vs Chains Explainer: case-studies\longchain-chains-vs-agents.md
  - Samples:
    - How-to: samples\how-to-deploy-flask-on-docker.md
    - Concept: samples\understanding-rbac.md
    - Reference: samples\cli-reference-sample.md
 
  - About the Portfolio: about/about.md
